"""create core schema

Revision ID: ed8229af8a7f
Revises: 
Create Date: 2026-09-07 18:30:24.143014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed8229af8a7f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS citext')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('imported_count', sa.Integer(), nullable=False),
    sa.Column('merged_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recruiters',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regions',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legacy_candidate_id', sa.Text(), nullable=True),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('region_code', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'screening', 'interviewing', 'withdrawn', name='candidate_status'), nullable=False),
    sa.Column('applied_date', sa.Date(), nullable=True),
    sa.Column('salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_code'], ['regions.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_candidates_legacy_candidate_id'), 'candidates', ['legacy_candidate_id'], unique=False)
    op.create_index('ix_candidates_region_applied_date_id', 'candidates', ['region_code', sa.literal_column('applied_date DESC'), 'id'], unique=False)
    op.create_index('ix_candidates_region_code', 'candidates', ['region_code'], unique=False)
    op.create_index('ix_candidates_status', 'candidates', ['status'], unique=False)
    op.create_table('import_rejections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('raw_row', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recruiter_regions',
    sa.Column('recruiter_id', sa.Text(), nullable=False),
    sa.Column('region_code', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiters.id'], ),
    sa.ForeignKeyConstraint(['region_code'], ['regions.code'], ),
    sa.PrimaryKeyConstraint('recruiter_id', 'region_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recruiter_regions')
    op.drop_table('import_rejections')
    op.drop_index('ix_candidates_status', table_name='candidates')
    op.drop_index('ix_candidates_region_code', table_name='candidates')
    op.drop_index('ix_candidates_region_applied_date_id', table_name='candidates')
    op.drop_index(op.f('ix_candidates_legacy_candidate_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_table('regions')
    op.drop_table('recruiters')
    op.drop_table('import_batches')
    # ### end Alembic commands ###

    sa.Enum(name='candidate_status').drop(op.get_bind(), checkfirst=True)
    op.execute('DROP EXTENSION IF EXISTS citext')
